DOLEV_STRONG_PROTOCOL = "DolevStrong"
STREAMLET_PROTOCOL = "Streamlet"
ADVERSARY_DONOTHING_PROTOCOL = "DoNothing"
ADVERSARY_RANDOMBROADCAST_PROTOCOL = "RandomBroadcast"
DOLEV_STRONG_ADVERSARY = "DolevStrongAdversary"

MESSAGES_PER_NODE_DELIM = "||"
INTRA_MESSAGE_DELIM = "|"
